apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nivelepsilon.com
  namespace: wordpress
spec:
  secretName: nivelepsilon-com-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
  - nivelepsilon.com