apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nivelepsilon-n0-reply-com
spec:
  secretName: nivelepsilon-n0-reply-com-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
  - nivelepsilon.n0-reply.com